# Generated by Django 2.2.4 on 2020-05-20 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_pub_ip', models.CharField(blank=True, max_length=100)),
                ('asset_priv_ip', models.CharField(blank=True, max_length=100)),
                ('asset_region', models.CharField(blank=True, max_length=100)),
                ('asset_type', models.CharField(blank=True, max_length=100)),
                ('asset_is_public', models.BooleanField()),
                ('asset_egress_applied', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
