# Generated by Django 2.2.4 on 2020-05-20 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aws', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='asset_hash',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
