# Generated by Django 2.2.4 on 2020-05-21 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aws', '0003_auto_20200521_0430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='asset_is_public',
            field=models.BooleanField(null=True),
        ),
    ]
