# Generated by Django 2.2.4 on 2020-05-21 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aws', '0005_auto_20200521_0452'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='asset_hash',
            new_name='hash',
        ),
        migrations.RenameField(
            model_name='asset',
            old_name='asset_instance_id',
            new_name='instance_id',
        ),
        migrations.RenameField(
            model_name='asset',
            old_name='asset_is_public',
            new_name='is_public',
        ),
        migrations.RenameField(
            model_name='asset',
            old_name='asset_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='asset',
            old_name='asset_priv_ip',
            new_name='priv_ip',
        ),
        migrations.RenameField(
            model_name='asset',
            old_name='asset_pub_ip',
            new_name='pub_ip',
        ),
        migrations.RenameField(
            model_name='asset',
            old_name='asset_sgId',
            new_name='sgId',
        ),
        migrations.RenameField(
            model_name='asset',
            old_name='asset_type',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='asset',
            old_name='asset_zone',
            new_name='zone',
        ),
    ]
